### ISSUE TITLE
Add Farm products API endpoints for Marketplace

### ISSUE THREAD

**Issue by mihrab34** [Cubeseed/Backend#80]
**Description**

As a buyer of farm products in Nigeria, I want to be able to easily access a database of farms across the country through a supplier connection, so that I can quickly find and purchase the farm products I need, including fruits, vegetables, grains, and other essential products

**Todo**

- [ ] create farm product model
- [ ] add endpoints to get all farm products
- [ ] add necessary unit test

**Comment by Reid-T-W** [comment]
Hi @mihrab34, there is an existing app called commodity, it refers to farm products. I think you can modify it to satisfy your use case, as the commodity model is already interlinked with the farm and cluster model.

**Comment by mihrab34** [comment]
Thanks @Reid-T-W  . i'll check it out
